package com.mavenMVC.entity;
// Generated 2016-4-11 17:07:57 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "Admin"
        , catalog = "cloudHospital"
)
public class Admin implements java.io.Serializable {


    private Long adminId;
    private String adminName;
    private String adminPassword;
    private Long createTime;
    private Long lastModTime;

    public Admin() {
    }

    public Admin(String adminName, String adminPassword, Long createTime, Long lastModTime) {
        this.adminName = adminName;
        this.adminPassword = adminPassword;
        this.createTime = createTime;
        this.lastModTime = lastModTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ADMIN_ID", unique = true, nullable = false)
    public Long getAdminId() {
        return this.adminId;
    }

    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    @Column(name = "ADMIN_NAME")
    public String getAdminName() {
        return this.adminName;
    }

    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }

    @Column(name = "ADMIN_PASSWORD")
    public String getAdminPassword() {
        return this.adminPassword;
    }

    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword;
    }

    @Column(name = "CREATE_TIME")
    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    @Column(name = "LAST_MOD_TIME")
    public Long getLastModTime() {
        return this.lastModTime;
    }

    public void setLastModTime(Long lastModTime) {
        this.lastModTime = lastModTime;
    }


}


