package com.mavenMVC.entity;
// Generated 2016-5-23 18:01:24 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Article generated by hbm2java
 */
@Entity
@Table(name = "Collection"
        , catalog = "cloudHospital"
)
public class Collection implements java.io.Serializable {


    private Long collectionId;
    private Long userId;
    private Long articleId;
    private Long doctorId;
    private Integer collectionType;
    private Long createTime;
    private Long lastModTime;

    public Collection() {
    }

    public Collection(Long userId, Long articleId, Long doctorId, Integer collectionType, Long createTime, Long lastModTime) {
        this.userId = userId;
        this.articleId = articleId;
        this.doctorId = doctorId;
        this.collectionType = collectionType;
        this.createTime = createTime;
        this.lastModTime = lastModTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "COLLECTION_ID")
    public Long getCollectionId() {
        return collectionId;
    }

    public void setCollectionId(Long collectionId) {
        this.collectionId = collectionId;
    }

    @Column(name = "USER_ID")
    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Column(name = "ARTICLE_ID")
    public Long getArticleId() {
        return articleId;
    }

    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    @Column(name = "DOCTOR_ID")
    public Long getDoctorId() {
        return doctorId;
    }

    public void setDoctorId(Long doctorId) {
        this.doctorId = doctorId;
    }

    @Column(name = "COLLECTION_TYPE")
    public Integer getCollectionType() {
        return collectionType;
    }

    public void setCollectionType(Integer collectionType) {
        this.collectionType = collectionType;
    }

    @Column(name = "CREATE_TIME")
    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    @Column(name = "LAST_MOD_TIME")
    public Long getLastModTime() {
        return this.lastModTime;
    }

    public void setLastModTime(Long lastModTime) {
        this.lastModTime = lastModTime;
    }


}


