package com.mavenMVC.entity;
// Generated 2016-5-9 16:07:38 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "Department"
        , catalog = "cloudHospital"
)
public class Department implements java.io.Serializable {


    private Long departmentId;
    private String departmentName;
    private Long createTime;
    private Long lastModTime;

    public Department() {
    }

    public Department(String departmentName, Long createTime, Long lastModTime) {
        this.departmentName = departmentName;
        this.createTime = createTime;
        this.lastModTime = lastModTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "DEPARTMENT_ID", unique = true, nullable = false)
    public Long getDepartmentId() {
        return this.departmentId;
    }

    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }

    @Column(name = "DEPARTMENT_NAME", length = 45)
    public String getDepartmentName() {
        return this.departmentName;
    }

    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    @Column(name = "CREATE_TIME")
    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    @Column(name = "LAST_MOD_TIME")
    public Long getLastModTime() {
        return this.lastModTime;
    }

    public void setLastModTime(Long lastModTime) {
        this.lastModTime = lastModTime;
    }


}


