package com.mavenMVC.entity;
// Generated 2016-5-9 16:07:38 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Hospital generated by hbm2java
 */
@Entity
@Table(name="Hospital"
    ,catalog="cloudHospital"
)
public class Hospital  implements java.io.Serializable {


     private Long hospitalId;
     private String hospitalName;
     private String hospitalAddress;
     private Long createTime;
     private Long lastModTime;

    public Hospital() {
    }

    public Hospital(String hospitalName, String hospitalAddress, Long createTime, Long lastModTime) {
       this.hospitalName = hospitalName;
       this.hospitalAddress = hospitalAddress;
       this.createTime = createTime;
       this.lastModTime = lastModTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="HOSPITAL_ID", unique=true, nullable=false)
    public Long getHospitalId() {
        return this.hospitalId;
    }
    
    public void setHospitalId(Long hospitalId) {
        this.hospitalId = hospitalId;
    }
    
    @Column(name="HOSPITAL_NAME")
    public String getHospitalName() {
        return this.hospitalName;
    }
    
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName;
    }
    
    @Column(name="HOSPITAL_ADDRESS", length=1022)
    public String getHospitalAddress() {
        return this.hospitalAddress;
    }
    
    public void setHospitalAddress(String hospitalAddress) {
        this.hospitalAddress = hospitalAddress;
    }
    
    @Column(name="CREATE_TIME")
    public Long getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="LAST_MOD_TIME")
    public Long getLastModTime() {
        return this.lastModTime;
    }
    
    public void setLastModTime(Long lastModTime) {
        this.lastModTime = lastModTime;
    }




}


