package com.mavenMVC.entity;
// Generated 2016-5-23 18:01:24 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Response generated by hbm2java
 */
@Entity
@Table(name = "Message"
        , catalog = "cloudHospital"
)
public class Message implements java.io.Serializable {

    private long messageId;
    private String messageContent;
    private Integer messageType;
    private Long messageUserId;
    private Integer messageUserType;
    private Long createTime;
    private Long lastModTime;

    public Message() {
    }

    public Message(String messageContent, Integer messageType, Long messageUserId, Integer messageUserType, Long createTime, Long lastModTime) {
        this.messageContent = messageContent;
        this.messageType = messageType;
        this.messageUserId = messageUserId;
        this.messageUserType = messageUserType;
        this.createTime = createTime;
        this.lastModTime = lastModTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "MESSAGE_ID")
    public long getMessageId() {
        return messageId;
    }

    public void setMessageId(long messageId) {
        this.messageId = messageId;
    }

    @Column(name = "MESSAGE_CONTENT")
    public String getMessageContent() {
        return messageContent;
    }

    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent;
    }

    @Column(name = "MESSAGE_TYPE")
    public Integer getMessageType() {
        return messageType;
    }

    public void setMessageType(Integer messageType) {
        this.messageType = messageType;
    }

    @Column(name = "MESSAGE_USERID")
    public Long getMessageUserId() {
        return messageUserId;
    }

    public void setMessageUserId(Long messageUserId) {
        this.messageUserId = messageUserId;
    }

    @Column(name = "MESSAGE_USERTYPE")
    public Integer getMessageUserType() {
        return messageUserType;
    }

    public void setMessageUserType(Integer messageUserType) {
        this.messageUserType = messageUserType;
    }

    @Column(name = "CREATE_TIME")
    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    @Column(name = "LAST_MOD_TIME")
    public Long getLastModTime() {
        return this.lastModTime;
    }

    public void setLastModTime(Long lastModTime) {
        this.lastModTime = lastModTime;
    }

}


