package com.mavenMVC.entity;
// Generated 2016-4-11 17:07:57 by Hibernate Tools 3.2.2.GA


import net.sf.json.JSONObject;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "Order"
        , catalog = "cloudHospital"
)
public class Order implements java.io.Serializable {

    private Long orderId;
    private Long orderPid;
    private Long orderDid;
    private Long orderRid;
    private int orderType;
    private Long orderDateTime;
    private Long orderProceedTime;
    private Integer orderStatus;
    private Integer orderPayStatus;
    private String orderPayChannel;
    private String orderComment;
    private Integer orderScore;
    private String orderRefuseReason;
    private String orderChargeId;
    private Integer orderPaidMoney;
    private Integer orderRefundMoney;
    private Integer orderSettledMoney;
    private Long createTime;
    private Long lastModTime;

    public Order() {
    }

    public Order(Long orderPid, Long orderDid, Long orderRid, int orderType, Long orderDateTime, Long orderProceedTime, Integer orderStatus,
                 Integer orderPayStatus, String orderPayChannel, String orderComment, Integer orderScore, String orderRefuseReason,
                 String orderChargeId, Integer orderPaidMoney, Integer orderRefundMoney,
                 Integer orderSettledMoney, Long createTime, Long lastModTime) {
        this.orderPid = orderPid;
        this.orderDid = orderDid;
        this.orderRid = orderRid;
        this.orderType = orderType;
        this.orderDateTime = orderDateTime;
        this.orderProceedTime = orderProceedTime;
        this.orderStatus = orderStatus;
        this.orderPayStatus = orderPayStatus;
        this.orderPayChannel = orderPayChannel;
        this.orderComment = orderComment;
        this.orderScore = orderScore;
        this.orderRefuseReason = orderRefuseReason;
        this.orderChargeId = orderChargeId;
        this.orderPaidMoney = orderPaidMoney;
        this.orderRefundMoney = orderRefundMoney;
        this.orderSettledMoney = orderSettledMoney;
        this.createTime = createTime;
        this.lastModTime = lastModTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ORDER_ID", unique = true, nullable = false)
    public Long getOrderId() {
        return this.orderId;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    @Column(name = "ORDER_PID")
    public Long getOrderPid() {
        return this.orderPid;
    }

    public void setOrderPid(Long orderPid) {
        this.orderPid = orderPid;
    }

    @Column(name = "ORDER_DID")
    public Long getOrderDid() {
        return this.orderDid;
    }

    public void setOrderDid(Long orderDid) {
        this.orderDid = orderDid;
    }

    @Column(name = "ORDER_RID")
    public Long getOrderRid() {
        return orderRid;
    }

    public void setOrderRid(Long orderRid) {
        this.orderRid = orderRid;
    }

    @Column(name = "ORDER_TYPE")
    public int getOrderType() {
        return orderType;
    }

    public void setOrderType(int orderType) {
        this.orderType = orderType;
    }

    @Column(name = "ORDER_DATE_TIME")
    public Long getOrderDateTime() {
        return this.orderDateTime;
    }

    public void setOrderDateTime(Long orderDateTime) {
        this.orderDateTime = orderDateTime;
    }

    @Column(name = "ORDER_PROCEED_TIME")
    public Long getOrderProceedTime() {
        return this.orderProceedTime;
    }

    public void setOrderProceedTime(Long orderProceedTime) {
        this.orderProceedTime = orderProceedTime;
    }

    @Column(name = "ORDER_STATUS")
    public Integer getOrderStatus() {
        return this.orderStatus;
    }

    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    @Column(name = "ORDER_PAY_STATUS")
    public Integer getOrderPayStatus() {
        return this.orderPayStatus;
    }

    public void setOrderPayStatus(Integer orderPayStatus) {
        this.orderPayStatus = orderPayStatus;
    }

    @Column(name = "ORDER_PAY_CHANNEL")
    public String getOrderPayChannel() {
        return orderPayChannel;
    }

    public void setOrderPayChannel(String orderPayChannel) {
        this.orderPayChannel = orderPayChannel;
    }

    @Column(name = "ORDER_COMMENT", length = 65535)
    public String getOrderComment() {
        return this.orderComment;
    }

    public void setOrderComment(String orderComment) {
        this.orderComment = orderComment;
    }

    @Column(name = "ORDER_SCORE")
    public Integer getOrderScore() {
        return orderScore;
    }

    public void setOrderScore(Integer orderScore) {
        this.orderScore = orderScore;
    }

    @Column(name = "ORDER_REFUSE_REASON")
    public String getOrderRefuseReason() {
        return orderRefuseReason;
    }

    public void setOrderRefuseReason(String orderRefuseReason) {
        this.orderRefuseReason = orderRefuseReason;
    }

    @Column(name = "ORDER_CHARGE_ID")
    public String getOrderChargeId() {
        return orderChargeId;
    }

    public void setOrderChargeId(String orderChargeId) {
        this.orderChargeId = orderChargeId;
    }

    @Column(name = "ORDER_PAID_MONEY")
    public Integer getOrderPaidMoney() {
        return orderPaidMoney;
    }

    public void setOrderPaidMoney(Integer orderPaidMoney) {
        this.orderPaidMoney = orderPaidMoney;
    }

    @Column(name = "ORDER_REFUND_MONEY")
    public Integer getOrderRefundMoney() {
        return orderRefundMoney;
    }

    public void setOrderRefundMoney(Integer orderRefundMoney) {
        this.orderRefundMoney = orderRefundMoney;
    }

    @Column(name = "ORDER_SETTLED_MONEY")
    public Integer getOrderSettledMoney() {
        return orderSettledMoney;
    }

    public void setOrderSettledMoney(Integer orderSettledMoney) {
        this.orderSettledMoney = orderSettledMoney;
    }

    @Column(name = "CREATE_TIME")
    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    @Column(name = "LAST_MOD_TIME")
    public Long getLastModTime() {
        return this.lastModTime;
    }

    public void setLastModTime(Long lastModTime) {
        this.lastModTime = lastModTime;
    }

    public JSONObject commentJSON() {
        JSONObject jo = new JSONObject();
        jo.put("orderId", this.orderId);
        jo.put("orderComment", this.orderComment);
        jo.put("orderScore", this.orderScore);
        jo.put("orderDateTime", this.orderDateTime);
        return jo;
    }

    public JSONObject moneyJSON() {
        JSONObject jo = new JSONObject();
        jo.put("orderId", this.orderId);
        jo.put("orderSettledMoney", this.orderSettledMoney);
        jo.put("orderDateTime", this.orderDateTime);
        jo.put("createTime", this.createTime);
        return jo;
    }

}


