package com.mavenMVC.entity;
// Generated 2016-5-9 16:07:38 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Title generated by hbm2java
 */
@Entity
@Table(name = "Record"
        , catalog = "cloudHospital"
)
public class Record implements java.io.Serializable {


    private Long recordId;
    private Long recordPatientId;
    private String recordDiagnosis;
    private String recordName;
    private String recordImage;
    private String recordDescription;
    private int recordType;
    private int recordStatus;
    private Long createTime;
    private Long lastModTime;

    public Record() {
    }

    public Record(String recordName, String recordDiagnosis, Long recordPatientId, String recordImage, String recordDescription, int recordType, Long createTime, Long lastModTime) {
        this.recordName = recordName;
        this.recordDiagnosis = recordDiagnosis;
        this.recordPatientId = recordPatientId;
        this.recordImage = recordImage;
        this.recordDescription = recordDescription;
        this.recordType = recordType;
        this.recordStatus = recordStatus;
        this.createTime = createTime;
        this.lastModTime = lastModTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "RECORD_ID", unique = true, nullable = false)
    public Long getRecordId() {
        return recordId;
    }

    public void setRecordId(Long recordId) {
        this.recordId = recordId;
    }

    @Column(name = "RECORD_PATIENT_ID")
    public Long getRecordPatientId() {
        return recordPatientId;
    }

    public void setRecordPatientId(Long recordPatientId) {
        this.recordPatientId = recordPatientId;
    }

    @Column(name = "RECORD_DIAGNOSIS")
    public String getRecordDiagnosis() {
        return recordDiagnosis;
    }

    public void setRecordDiagnosis(String recordDiagnosis) {
        this.recordDiagnosis = recordDiagnosis;
    }

    @Column(name = "RECORD_NAME", length = 45)
    public String getRecordName() {
        return recordName;
    }

    public void setRecordName(String recordName) {
        this.recordName = recordName;
    }

    @Column(name = "RECORD_IMAGE", length = 1022)
    public String getRecordImage() {
        return recordImage;
    }

    public void setRecordImage(String recordImage) {
        this.recordImage = recordImage;
    }

    @Column(name = "RECORD_DESCRIPTION", length = 65535)
    public String getRecordDescription() {
        return recordDescription;
    }

    public void setRecordDescription(String recordDescription) {
        this.recordDescription = recordDescription;
    }

    @Column(name = "RECORD_TYPE")
    public int getRecordType() {
        return recordType;
    }

    public void setRecordType(int recordType) {
        this.recordType = recordType;
    }

    @Column(name = "RECORD_STATUS")
    public int getRecordStatus() {
        return recordStatus;
    }

    public void setRecordStatus(int recordStatus) {
        this.recordStatus = recordStatus;
    }

    @Column(name = "CREATE_TIME")
    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    @Column(name = "LAST_MOD_TIME")
    public Long getLastModTime() {
        return this.lastModTime;
    }

    public void setLastModTime(Long lastModTime) {
        this.lastModTime = lastModTime;
    }


}


