package com.mavenMVC.entity;
// Generated 2016-7-9 14:11:08 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Schedule generated by hbm2java
 */
@Entity
@Table(name = "Schedule"
        , catalog = "cloudHospital"
)
public class Schedule implements java.io.Serializable {


    private Long scheduleId;
    private Long scheduleDid;
    private String scheduleTitle;
    private String scheduleDay;
    private String scheduleStartTime;
    private String scheduleEndTime;
    private boolean scheduleAlert = false;
    private Long createTime;
    private Long lastModTime;

    public Schedule() {
    }

    public Schedule(Long scheduleDid, String scheduleTitle, String scheduleDay, String scheduleStartTime, String scheduleEndTime, boolean scheduleAlert, Long createTime, Long lastModTime) {
        this.scheduleDid = scheduleDid;
        this.scheduleTitle = scheduleTitle;
        this.scheduleDay = scheduleDay;
        this.scheduleStartTime = scheduleStartTime;
        this.scheduleEndTime = scheduleEndTime;
        this.scheduleAlert = scheduleAlert;
        this.createTime = createTime;
        this.lastModTime = lastModTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "SCHEDULE_ID", unique = true, nullable = false)
    public Long getScheduleId() {
        return this.scheduleId;
    }

    public void setScheduleId(Long scheduleId) {
        this.scheduleId = scheduleId;
    }

    @Column(name = "SCHEDULE_DID")
    public Long getScheduleDid() {
        return this.scheduleDid;
    }

    public void setScheduleDid(Long scheduleDid) {
        this.scheduleDid = scheduleDid;
    }

    @Column(name = "SCHEDULE_TITLE", length = 45)
    public String getScheduleTitle() {
        return this.scheduleTitle;
    }

    public void setScheduleTitle(String scheduleTitle) {
        this.scheduleTitle = scheduleTitle;
    }

    @Column(name = "SCHEDULE_DAY", length = 45)
    public String getScheduleDay() {
        return this.scheduleDay;
    }

    public void setScheduleDay(String scheduleDay) {
        this.scheduleDay = scheduleDay;
    }

    @Column(name = "SCHEDULE_START_TIME")
    public String getScheduleStartTime() {
        return this.scheduleStartTime;
    }

    public void setScheduleStartTime(String scheduleStartTime) {
        this.scheduleStartTime = scheduleStartTime;
    }

    @Column(name = "SCHEDULE_END_TIME")
    public String getScheduleEndTime() {
        return this.scheduleEndTime;
    }

    public void setScheduleEndTime(String scheduleEndTime) {
        this.scheduleEndTime = scheduleEndTime;
    }

    @Column(name = "SCHEDULE_ALERT")
    public boolean getScheduleAlert() {
        return this.scheduleAlert;
    }

    public void setScheduleAlert(boolean scheduleAlert) {
        this.scheduleAlert = scheduleAlert;
    }

    @Column(name = "CREATE_TIME")
    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    @Column(name = "LAST_MOD_TIME")
    public Long getLastModTime() {
        return this.lastModTime;
    }

    public void setLastModTime(Long lastModTime) {
        this.lastModTime = lastModTime;
    }


}


