package com.mavenMVC.entity;
// Generated 2016-5-9 16:07:38 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Title generated by hbm2java
 */
@Entity
@Table(name = "Title"
        , catalog = "cloudHospital"
)
public class Title implements java.io.Serializable {

    private Long titleId;
    private String titleName;
    private Long createTime;
    private Long lastModTime;

    public Title() {
    }

    public Title(String titleName, Long createTime, Long lastModTime) {
        this.titleName = titleName;
        this.createTime = createTime;
        this.lastModTime = lastModTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "TITLE_ID", unique = true, nullable = false)
    public Long getTitleId() {
        return this.titleId;
    }

    public void setTitleId(Long titleId) {
        this.titleId = titleId;
    }

    @Column(name = "TITLE_NAME", length = 45)
    public String getTitleName() {
        return this.titleName;
    }

    public void setTitleName(String titleName) {
        this.titleName = titleName;
    }

    @Column(name = "CREATE_TIME")
    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    @Column(name = "LAST_MOD_TIME")
    public Long getLastModTime() {
        return this.lastModTime;
    }

    public void setLastModTime(Long lastModTime) {
        this.lastModTime = lastModTime;
    }

}


