package com.mavenMVC.entity;
// Generated 2016-4-11 17:07:57 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "User"
        , catalog = "cloudHospital"
)
public class User implements java.io.Serializable {

    private Long userId;
    private String userName;
    private Integer userStatus;
    private Integer userAge;
    private Integer userSex;
    private String userPassword;
    private String userCellphone;
    private String userBirthDay;
    private String userToken;
    private String userHeadimage;
    private Integer userCertificateType;
    private String userCertificateDetail;
    private Integer userMoney;
    private String userInstallationId;
    private Integer userOsType;
    private Integer userLogin;
    private String userImToken;
    private Long createTime;
    private Long lastModTime;

    public User() {
    }

    public User(String userName, Integer userStatus, Integer userAge, Integer userSex, String userPassword, String userCellphone, String userBirthDay, String userToken, String userHeadimage, Integer userCertificateType, String userCertificateDetail, Integer userMoney, String userInstallationId, Integer userOsType, Integer userLogin, String userImToken, Long createTime, Long lastModTime) {
        this.userName = userName;
        this.userStatus = userStatus;
        this.userAge = userAge;
        this.userSex = userSex;
        this.userPassword = userPassword;
        this.userCellphone = userCellphone;
        this.userBirthDay = userBirthDay;
        this.userToken = userToken;
        this.userHeadimage = userHeadimage;
        this.userCertificateType = userCertificateType;
        this.userCertificateDetail = userCertificateDetail;
        this.userMoney = userMoney;
        this.userInstallationId = userInstallationId;
        this.userOsType = userOsType;
        this.userLogin = userLogin;
        this.userImToken = userImToken;
        this.createTime = createTime;
        this.lastModTime = lastModTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "USER_ID", unique = true, nullable = false)
    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Column(name = "USER_NAME")
    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Column(name = "USER_AGE")
    public Integer getUserAge() {
        return userAge;
    }

    public void setUserAge(Integer userAge) {
        this.userAge = userAge;
    }

    @Column(name = "USER_SEX")
    public Integer getUserSex() {
        return userSex;
    }

    public void setUserSex(Integer userSex) {
        this.userSex = userSex;
    }

    @Column(name = "USER_STATUS")
    public Integer getUserStatus() {
        return this.userStatus;
    }

    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    @Column(name = "USER_PASSWORD")
    public String getUserPassword() {
        return this.userPassword;
    }

    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    @Column(name = "USER_CELLPHONE", length = 45)
    public String getUserCellphone() {
        return this.userCellphone;
    }

    public void setUserCellphone(String userCellphone) {
        this.userCellphone = userCellphone;
    }

    @Column(name = "USER_BIRTHDAY", length = 45)
    public String getUserBirthDay() {
        return userBirthDay;
    }

    public void setUserBirthDay(String userBirthDay) {
        this.userBirthDay = userBirthDay;
    }

    @Column(name = "USER_TOKEN", length = 45)
    public String getUserToken() {
        return this.userToken;
    }

    public void setUserToken(String userToken) {
        this.userToken = userToken;
    }

    @Column(name = "USER_HEADIMAGE", length = 1022)
    public String getUserHeadimage() {
        return this.userHeadimage;
    }

    public void setUserHeadimage(String userHeadimage) {
        this.userHeadimage = userHeadimage;
    }

    @Column(name = "USER_CERTIFICATE_TYPE")
    public Integer getUserCertificateType() {
        return userCertificateType;
    }

    public void setUserCertificateType(Integer userCertificateType) {
        this.userCertificateType = userCertificateType;
    }

    @Column(name = "USER_CERTIFICATE_DETAIL", length = 1022)
    public String getUserCertificateDetail() {
        return userCertificateDetail;
    }

    public void setUserCertificateDetail(String userCertificateDetail) {
        this.userCertificateDetail = userCertificateDetail;
    }

    @Column(name = "USER_MONEY")
    public Integer getUserMoney() {
        return userMoney;
    }

    public void setUserMoney(Integer userMoney) {
        this.userMoney = userMoney;
    }

    @Column(name = "USER_INSTALLATION_ID")
    public String getUserInstallationId() {
        return userInstallationId;
    }

    public void setUserInstallationId(String userInstallationId) {
        this.userInstallationId = userInstallationId;
    }

    @Column(name = "USER_OS_TYPE")
    public Integer getUserOsType() {
        return userOsType;
    }

    public void setUserOsType(Integer userOsType) {
        this.userOsType = userOsType;
    }

    @Column(name = "USER_LOGIN")
    public Integer getUserLogin(){
        return this.userLogin;
    }

    public void setUserLogin(Integer userLogin){
        this.userLogin = userLogin;
    }

    @Column(name = "USER_IM_TOKEN")
    public String getUserImToken() {
        return userImToken;
    }

    public void setUserImToken(String userImToken) {
        this.userImToken = userImToken;
    }

    @Column(name = "CREATE_TIME")
    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    @Column(name = "LAST_MOD_TIME")
    public Long getLastModTime() {
        return this.lastModTime;
    }

    public void setLastModTime(Long lastModTime) {
        this.lastModTime = lastModTime;
    }

}


